### ISSUE TITLE
Add support for other popular distributions

### ISSUE THREAD

**Issue by TurboTurtle** [sosreport/sos-collector#2]
Right now, sos-collector only works on RH-family hosts. This is because `sosnode.get_release()` only has logic for those distributions, which then sets the package manager command. This should be trivial to add other distributions, but doing it cleanly is key. Admittedly, it's also been over 5 years since I've used a non-RH distro, so I've not kept up non-rpm package managers which has directly led to this situation.

I'd like to avoid a full-blown mechanism like sosreport's policy class, since the importance of the host's distribution as far as sos-collector is concerned is far more limited; we need to set the appropriate package manager only to then query installed packages to determine a cluster type. Beyond that, it is irrelevant what distribution is in use.

**Comment by bmr-cymru** [comment]
It should be possible for us to lift most of that straight out of the Debian / Ubuntu sos policy classes - and if we're lucky, get some of the sos folks for those distributions to test the changes ;-)

**Comment by TurboTurtle** [comment]
So, as of 1a6985c this should be dead simple to add distro support. We'd only need to define a `Ubuntu` class that sets the relevant package manager and checks a distro-specifying file like `/etc/os-release` (and potentially different package names for the clusters we have profiles for right now).

That being said aside from a single VM I spun up to test sos parallelization I haven't touched a Debian/*buntu install in probably 6 years, so I have no idea about the desirability of s-c over there.

@battlemidget any thoughts on the 'sos-collector for Ubuntu' front?

**Comment by battlemidget** [comment]
I could see this being used in our Juju deployments, currently, there is https://github.com/juju/juju-crashdump and it's supports sosreport as a plugin. I wonder if there is a need to use sos-collector as a plugin instead? Outside of Juju, we have customers that deploy at scale with things like maas.io so I could definitely see this being useful there.

@BryanQuigley, @slashdd, thoughts?

**Comment by BryanQuigley** [comment]
For juju there is also https://jujucharms.com/u/sosreport-charmers/sosreport/5, but AFAIK it's currently unmaintained. 

I'll put reviewing this on my TODO list.

Aside: I'm also using paramiko for a sosreport related project : https://gitlab.com/BryanQuigley/ScoutPlane

**Comment by bmr-cymru** [comment]
I think this is a good idea: it would be great to have `sosrepot` and `sos-collector` supported on the same distro families (or at least, the ones with a declared interest in it). It's consistent, clear to users, and fits in with the work we've done since 2010 to make `sos` a cross-distribution tool.

**Comment by BryanQuigley** [comment]
I found the issue requiring moving to using /etc/os-release instead of /etc/redhat_release -  Is there any reason to keep redhat checking that instead of just moving everyone over to /etc/os-release? AFAICT some of the code is in SoSNode and some in hosts.

We would also want to add a per OS variable for tracking sosreports package name.  
sos_package_name = 'sos' for RH, and sos_package_name = 'sosreport'  for Debian/Ubuntu.

Quick hacks to get it working on Ubuntu didn't work, so I'm going to try it out on Fedora when I next get some time.

**Comment by TurboTurtle** [comment]
> I found the issue requiring moving to using /etc/os-release instead of /etc/redhat_release - Is there any reason to keep redhat checking that instead of just moving everyone over to /etc/os-release? AFAICT some of the code is in SoSNode and some in hosts.
> 
The default is `/etc/os-release` - https://github.com/sosreport/sos-collector/blob/bf217f80d171c1db64da6239df4d3be8d9eea4c5/soscollector/hosts/__init__.py#L33,L35

So if you define a `UbuntuHost` class you wouldn't need to specify a release file.

E.G.:
```python
class UbuntuHost(SosHost):

    distribution = 'Ubuntu'
    package_manager = {
        'name': 'apt',
        'query': 'apt list'
    }

    def check_enabled(self, rel_string):
        return 'Ubuntu' in rel_string  # or what have you
```

As far as using `/etc/os-release` for RH hosts, I think we should keep consistent with `sos` where we can, which is also using `/etc/redhat-release`.

> We would also want to add a per OS variable for tracking sosreports package name.
> sos_package_name = 'sos' for RH, and sos_package_name = 'sosreport' for Debian/Ubuntu.
>
Ack. Easy enough.
 
We'd also need to adjust determining the version of the sos package, as right now it just works with `rpm` output.

> Quick hacks to get it working on Ubuntu didn't work, so I'm going to try it out on Fedora when I next get some time.

**Comment by TurboTurtle** [comment]
With Ubuntu support added, we hit the two biggest distro families out there now. I'm closing this, if there are other distros that can benefit from sos-collector we can add those as needed down the road.
